"""Bảo vệ ở mức CSDL: audit_log chỉ-thêm (trigger + GRANT), app không tạo được bảng,
model khớp lược đồ do Alembic tạo (ERD v1.8 mục 6)."""
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from app.core.database import engine

APP_DENIED = [
    "UPDATE audit_log SET target_entity = 'x'",
    "DELETE FROM audit_log",
    "TRUNCATE audit_log",
    "CREATE TABLE thu (x int)",
    "UPDATE alembic_version SET version_num = 'x'",
]


@pytest.mark.parametrize("sql", APP_DENIED)
def test_app_role_cannot_modify_protected_objects(users, sql):
    with engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text(sql))
    assert exc.value.orig.sqlstate == "42501"                  # insufficient_privilege


@pytest.mark.parametrize("sql", ["UPDATE audit_log SET target_entity = 'x'", "DELETE FROM audit_log",
                                 "TRUNCATE audit_log"])
def test_trigger_blocks_even_the_owner(owner_engine, users, sql):
    with owner_engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text(sql))
    assert exc.value.orig.sqlstate == "23514"                  # trigger append-only (ERD v1.8)


def test_actor_check_constraint(users):
    with engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text("INSERT INTO audit_log(action_type, target_entity) VALUES ('LOGIN', 'users')"))
    assert "chk_audit_log_actor" in str(exc.value)


def test_models_match_migrated_schema(users):
    """Chạy đúng `alembic check` (dùng env.py thật): model không lệch bảng do 0001 tạo."""
    cfg = Config(str(Path(__file__).resolve().parents[1] / "alembic.ini"))
    command.check(cfg)   # ném AutogenerateDiffsDetected nếu có khác biệt


def test_every_table_has_a_model(users):
    """Đủ 25 model: bảng nào thêm bằng migration cũng phải có model tương ứng."""
    from sqlalchemy import inspect

    from app.models import Base
    db_tables = set(inspect(engine).get_table_names()) - {"alembic_version"}
    assert len(db_tables) == 25
    assert set(Base.metadata.tables) == db_tables


def test_orm_roundtrip_patient_visit(users):
    """Ghi/đọc qua model bằng vai trò app: cột sinh tự động không bị ghi, CHECK sinh hiệu chạy."""
    import datetime

    import pytest
    from sqlalchemy.exc import IntegrityError

    from app.core.database import SessionLocal
    from app.models import Patient, Visit

    with SessionLocal() as db:
        p = Patient(full_name="Nguyễn Thị Ánh", date_of_birth=datetime.date(1990, 5, 1), gender="Female")
        db.add(p)
        db.flush()
        v = Visit(patient_id=p.patient_id, nurse_id=users["yta"].user_id, chief_complaint="Sốt",
                  vital_signs={"temperature_c": 38.5, "spo2_pct": 97})
        db.add(v)
        db.flush()
        db.refresh(v)
        assert v.status == "Waiting" and v.ai_status == "Pending" and v.red_flag_rule_type is None

        bad = Visit(patient_id=p.patient_id, nurse_id=users["yta"].user_id, chief_complaint="x",
                    vital_signs={"nhiet_do": 38})                  # khóa lạ
        db.add(bad)
        with pytest.raises(IntegrityError, match="chk_visit_vital_signs_keys"):
            db.flush()
        db.rollback()
