"""Bảo vệ ở mức CSDL: audit_log chỉ-thêm (trigger + GRANT), app không tạo được bảng,
model khớp lược đồ do Alembic tạo (ERD v1.8 mục 6)."""
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError

from app.core.database import engine

APP_DENIED = [
    "UPDATE audit_log SET target_entity = 'x'",
    "DELETE FROM audit_log",
    "TRUNCATE audit_log",
    "CREATE TABLE thu (x int)",
    "UPDATE alembic_version SET version_num = 'x'",
]


@pytest.mark.parametrize("sql", APP_DENIED)
def test_app_role_cannot_modify_protected_objects(users, sql):
    with engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text(sql))
    assert exc.value.orig.sqlstate == "42501"                  # insufficient_privilege


@pytest.mark.parametrize("sql", ["UPDATE audit_log SET target_entity = 'x'", "DELETE FROM audit_log",
                                 "TRUNCATE audit_log"])
def test_trigger_blocks_even_the_owner(owner_engine, users, sql):
    with owner_engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text(sql))
    assert exc.value.orig.sqlstate == "23514"                  # trigger append-only (ERD v1.8)


def test_actor_check_constraint(users):
    with engine.connect() as conn, pytest.raises(DBAPIError) as exc:
        conn.execute(text("INSERT INTO audit_log(action_type, target_entity) VALUES ('LOGIN', 'users')"))
    assert "chk_audit_log_actor" in str(exc.value)


def test_models_match_migrated_schema(users):
    """Chạy đúng `alembic check` (dùng env.py thật): model không lệch bảng do 0001 tạo."""
    cfg = Config(str(Path(__file__).resolve().parents[1] / "alembic.ini"))
    command.check(cfg)   # ném AutogenerateDiffsDetected nếu có khác biệt
